# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Procmail
version:      1.07
version_from: lib/Mail/Procmail.pm
installdirs:  site
requires:
    Getopt::Long:                  2
    LockFile::Simple:              0
    Mail::Internet:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
